services:
  api_service:
    build:
      context: .
      dockerfile: api_service/Dockerfile
    ports:
      - "8080:8080"
      - "50052:50052"
    depends_on:
      - db_service
      - kafka
    environment:
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - JWT_TOKEN_DURATION=3600
      - DB_SERVICE_HOST=db_service
      - DB_SERVICE_PORT=50051
      - GRPC_PORT=50052
      - HTTP_PORT=8080
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=task-events
      - KAFKA_ENABLED=true

  kafka_service:
    build:
      context: .
      dockerfile: kafka_service/Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=task-events
      - KAFKA_GROUP_ID=kafka-service
      - LOG_FILE_PATH=/var/log/kafka-service/events.logâ‰ 
    volumes:
      - kafka_logs:/var/log/kafka-service
    restart: on-failure

  db_service:
    build:
      context: .
      dockerfile: db_service/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=test_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: on-failure

  postgres:
    image: postgres:17.6
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_service/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  redis:
    image: redis:8.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  kafka_logs: